### ISSUE TITLE
Toughts on repo

### ISSUE THREAD

**Issue by Adevien** [hiroki19990625/EngineGL#4]
Hey, found your repo while looking for a way to handle 3d collision, you plan on adding it?

**Comment by hiroki19990625** [comment]
Hello. 3D collision already implemented
[Here is the implementation.] ( https://github.com/hiroki19990625/EngineGL/blob/master/EngineGL/Impl/Components/Collision.cs)

**Comment by Adevien** [comment]
Amazing, im trying to implement it on a server solution for unity3d, the gameobject structure you're using might work just right.

**Comment by Adevien** [comment]
Update: the collision does support multiple forms of collider or only the box type?

**Comment by hiroki19990625** [comment]
Only box types are supported.
We have plans to support it in the future.

**Comment by Adevien** [comment]
Great, i'm looking forward, Happens to know a solution for my case?

**Comment by hiroki19990625** [comment]
It is better to judge the hit of a polygon by boxes or circles.

**Comment by Adevien** [comment]
Yeah, but im looking for terrain collision too.
